import type { Metadata } from 'next';
import React from 'react';
import { Geist, Geist_Mono } from 'next/font/google';
import { Merriweather, Montserrat } from 'next/font/google';
import './globals.css';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

const merriweather = Merriweather({ subsets: ['latin'], weight: ['400', '700'] });
const montserrat = Montserrat({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${merriweather.className} ${montserrat.className} font-body antialiased`}>
        <div className="container mx-auto px-2 lg:px-4">
          <Navbar />
          <div className="min-h-[calc(100vh-160px)] border border-green-500">{children}</div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
